# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_rscriptbridge.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/02_rscriptbridge.ipynb 3
import json, os
import subprocess
import warnings

from functools import reduce


