name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: python:3-bookworm
    steps: [uses: fastai/workflows/quarto-ghp@master]
